print("========== CATATAN BELANJA ==========")
print("========== Daftar 1 ==========")
Belanja = input("Daftar Belanja 1:")
print("========== Daftar 2 ==========")
Belanja2 = input("Daftar Belanja 2:")
print("Jawab dengan angka [1/2]")
print("1. Rubah Belanjaan")
print("2. Keluar")
pilihan = input("Masukkan Pilihan: ")
item1 = input("Masukkan nama item ke daftar 1: ")
dirubah = input("Masukkan index yang ingin dirubah: ")
item2 = input("Masukkan nama item ke daftar 2: ")
dirubah2 = input("Masukkan index yang ingin dirubah: ")
print("========== Daftar 1 ==========")
print(Belanja)
print("========== Daftar 2 ==========")
print(Belanja2)
