Nama = input("Masukkan nama Anda : ")
Kuliah = input("Masukkan mata kuliah : ")
Grup = input ("Masukkan grup : ")
print("Haloo!",Nama)
print(Nama[0:9],"tergabung dalam kelas",Kuliah,"pada grup",Grup)
